### ISSUE TITLE
[memory] 기억 목록 불러오기 구현 

### ISSUE THREAD

**Issue by HyeonJooo** [saem4stup/seom_server#15]
## 개요
기억 목록 불러오기 구현

## 작업내용
고인 기억페이지에서 기억 목록 불러오기 구현

## 주의사항
N/A
## 기타
N/A

**Comment by JinHoLeeee** [comment]
기억 목록=게시글 인가여???

**Comment by HyeonJooo** [comment]
@JinHoLeeee 
![image](https://user-images.githubusercontent.com/58289478/130358767-ae240d39-07bc-4387-9d37-1e7c4e2ae30e.png)
이쪽 뷰 입니당

**Comment by JinHoLeeee** [comment]
넴넴 답장 감사함다~
